Example\Lib\Entities\Jobs:
    type: entity
    table: JOBS
    id:
        jobId:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
                comment: 'Primary key of jobs table.'
            id: true
            column: JOB_ID
            generator:
                strategy: SEQUENCE
    fields:
        jobTitle:
            type: string
            nullable: false
            length: 35
            options:
                fixed: false
                comment: 'A not null column that shows job title, e.g. AD_VP, FI_ACCOUNTANT'
            column: JOB_TITLE
        minSalary:
            type: integer
            nullable: true
            options:
                unsigned: false
                comment: 'Minimum salary for a job title.'
            column: MIN_SALARY
        maxSalary:
            type: integer
            nullable: true
            options:
                unsigned: false
                comment: 'Maximum salary for a job title'
            column: MAX_SALARY
    lifecycleCallbacks: {  }
